
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package es4;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION = 17;
  public static final int GE = 47;
  public static final int ENDVAR = 19;
  public static final int INTEGER = 14;
  public static final int INTEGER_CONST = 9;
  public static final int SEMI = 4;
  public static final int OUT = 26;
  public static final int MINUS = 41;
  public static final int REF = 20;
  public static final int WRITE = 28;
  public static final int TYPERETURN = 22;
  public static final int NOT = 52;
  public static final int AND = 44;
  public static final int LT = 48;
  public static final int RPAR = 21;
  public static final int ENDFUNCTION = 23;
  public static final int ENDPROCEDURE = 25;
  public static final int OR = 45;
  public static final int COMMA = 7;
  public static final int WRITERETURN = 29;
  public static final int DIV = 43;
  public static final int PLUS = 40;
  public static final int ASSIGN = 5;
  public static final int IF = 32;
  public static final int ENDWHILE = 38;
  public static final int ID = 6;
  public static final int LE = 49;
  public static final int EOF = 0;
  public static final int BOOLEAN = 16;
  public static final int RETURN = 27;
  public static final int TRUE = 11;
  public static final int error = 1;
  public static final int EQ = 50;
  public static final int DOLLARSIGN = 39;
  public static final int REAL = 13;
  public static final int TIMES = 42;
  public static final int COLON = 3;
  public static final int ENDIF = 33;
  public static final int ELSE = 35;
  public static final int READ = 30;
  public static final int WHILE = 36;
  public static final int REAL_CONST = 8;
  public static final int THEN = 31;
  public static final int NE = 51;
  public static final int LPAR = 18;
  public static final int STRING = 15;
  public static final int FALSE = 12;
  public static final int STRING_CONST = 10;
  public static final int GT = 46;
  public static final int VAR = 2;
  public static final int ELIF = 34;
  public static final int PROCEDURE = 24;
  public static final int DO = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "COLON",
  "SEMI",
  "ASSIGN",
  "ID",
  "COMMA",
  "REAL_CONST",
  "INTEGER_CONST",
  "STRING_CONST",
  "TRUE",
  "FALSE",
  "REAL",
  "INTEGER",
  "STRING",
  "BOOLEAN",
  "FUNCTION",
  "LPAR",
  "ENDVAR",
  "REF",
  "RPAR",
  "TYPERETURN",
  "ENDFUNCTION",
  "PROCEDURE",
  "ENDPROCEDURE",
  "OUT",
  "RETURN",
  "WRITE",
  "WRITERETURN",
  "READ",
  "THEN",
  "IF",
  "ENDIF",
  "ELIF",
  "ELSE",
  "WHILE",
  "DO",
  "ENDWHILE",
  "DOLLARSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "AND",
  "OR",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT"
  };
}

